package pers.jay.wanandroid.model.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import pers.jay.wanandroid.model.Article;
import pers.jay.wanandroid.model.ArticleInfo;

import pers.jay.wanandroid.model.dao.ArticleDao;
import pers.jay.wanandroid.model.dao.ArticleInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig articleDaoConfig;
    private final DaoConfig articleInfoDaoConfig;

    private final ArticleDao articleDao;
    private final ArticleInfoDao articleInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        articleDaoConfig = daoConfigMap.get(ArticleDao.class).clone();
        articleDaoConfig.initIdentityScope(type);

        articleInfoDaoConfig = daoConfigMap.get(ArticleInfoDao.class).clone();
        articleInfoDaoConfig.initIdentityScope(type);

        articleDao = new ArticleDao(articleDaoConfig, this);
        articleInfoDao = new ArticleInfoDao(articleInfoDaoConfig, this);

        registerDao(Article.class, articleDao);
        registerDao(ArticleInfo.class, articleInfoDao);
    }
    
    public void clear() {
        articleDaoConfig.clearIdentityScope();
        articleInfoDaoConfig.clearIdentityScope();
    }

    public ArticleDao getArticleDao() {
        return articleDao;
    }

    public ArticleInfoDao getArticleInfoDao() {
        return articleInfoDao;
    }

}
